In [1]:
import random as random
import Bio
import numpy as np
import sys
import os
import networkx as nx
import random as random
from tqdm import tqdm # loading bar
from utils_copy import linear_C, get_cost_2, get_sequence_string, parse_fasta_multiple, create_score_matrix, write_alignments_to_file, linear_backtrack, fill_graph,new_sp_approxi_combi
from utils_copy import convert_to_desired_format_nr_version, compute_cost, my_traversal_simply, extend_alignment_chaos, find_min_span_edges_testing, parse_fasta_multiple_remove_n
import timeit
from utils_copy import al_integrity_testt
from old_for_testing.sp_approx import sp_approx
from old_for_testing.utils import *
from functions_multiple_version import *

score_matrix={'a': {'a': 0, 'c': 5, 'g': 2, 't': 5}, 'c': {'a': 5, 'c': 0, 'g': 5, 't': 2}, 'g': {'a': 2, 'c': 5, 'g': 0, 't': 5}, 't': {'a': 5, 'c': 2, 'g': 5, 't': 0}}
gap_cost=5



In [7]:
random_sequences_collection[0]

#acaagttta , atatcta

['gcgtacttc',
 'accaacac',
 'acaagttta',
 'atatcta',
 'atgatg',
 'ttttt',
 'gaaagtggt',
 'tttctcat',
 'gctcg',
 'tcgaa']

In [3]:
random_sequences_collection=[]
for i in range(0,100):
    random_pile=[]
    for j in range (0,10):
        a_sequence=[]
        for k in range(0,random.randrange(5,10)):
            a_sequence.append(random.choice(['a','c','t','g']))
        a_sequence=''.join(a_sequence)
        random_pile.append(a_sequence)

    random_sequences_collection.append(random_pile)

print(random_sequences_collection)

[['gcgtacttc', 'accaacac', 'acaagttta', 'atatcta', 'atgatg', 'ttttt', 'gaaagtggt', 'tttctcat', 'gctcg', 'tcgaa'], ['tgcttcc', 'ggcttcccc', 'gacaagcg', 'cgcttc', 'gcttga', 'cgatggg', 'actatc', 'agagg', 'catcccctg', 'aatggcc'], ['gtacg', 'acttcg', 'cgaacc', 'taacccc', 'gccgt', 'tcttgatt', 'ggatgc', 'ctagaag', 'ttcga', 'ccacacga'], ['actga', 'acctga', 'tttccctac', 'tcaatc', 'aacgg', 'aaggccaac', 'cggcgaa', 'tgcaactt', 'aacgg', 'ccgcga'], ['aactac', 'gatacc', 'acgata', 'cgaccc', 'gttgga', 'atctacggt', 'tccaatgc', 'ctgtaa', 'taactttgc', 'cgtcgtact'], ['tccgat', 'atcatg', 'ttttcgaag', 'atatc', 'ctgcttat', 'gcagc', 'gactgca', 'tgtgaggt', 'aggccgcg', 'ggtttatt'], ['tgcacg', 'ggaaa', 'acctaac', 'ggggag', 'cggtaaca', 'acgccttgt', 'caagt', 'tagtgttc', 'aacgtt', 'tcttatatc'], ['cagatgcga', 'tctgg', 'gatacca', 'atattgg', 'cttgccgag', 'ttcta', 'ctctggtc', 'tactg', 'ggcgtc', 'ccgccccgg'], ['cagacaa', 'tgtttacc', 'ctgctaccc', 'ttgtg', 'tcaagga', 'acgcttcc', 'cagaacc', 'aataagc', 'cgattaagt', 'cgctcaga

In [6]:
costs_new=[]
costs_old=[]
for random_pile in random_sequences_collection:
    cost=new_assembly(random_pile,score_matrix,gap_cost)[4]
    costs_new.append(cost)
for random_pile in random_sequences_collection:
    cost=sp_approx(random_pile,score_matrix,gap_cost)[0]
    costs_old.append(cost)
print(costs_new)
print(costs_old)
costs_new=np.array(costs_new)
costs_old=np.array(costs_old)
differences=np.subtract(costs_new,costs_old)
print(differences)

Here comes the distance matrix produced by the alignments: 

[[ 0. 21. 18. 21. 24. 24. 28. 26. 25. 30.]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]]
Here comes the distance matrix produced by the alignments: 

[[ 0. 21. 18. 21. 24. 24. 28. 26. 25. 30.]
 [21.  0. 21. 22. 18. 28. 25. 21. 21. 19.]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan nan]]
Here comes the d

SystemExit: 

In [6]:
count=np.count_nonzero(differences<0)
print("Your algo was better than the classic in "+ str(count)+"% of the time")

NameError: name 'differences' is not defined